#! /bin/bash
mkdir /home/pi/pictures/$(date --date="tomorrow" +"%Y_%m_%d")
cd /home/pi/pictures/$(date --date="1 hour" +"%Y_%m_%d")
mkdir $(date --date="1 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="2 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="3 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="4 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="5 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="6 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="7 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="8 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="9 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="10 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="11 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="12 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="13 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="14 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="15 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="16 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="17 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="18 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="19 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="20 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="21 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="22 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="23 hour" +"%Y_%m_%d_%H")
mkdir $(date --date="24 hour" +"%Y_%m_%d_%H")

exit

